version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-fbla-01"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o52zwxbajew3"
s3_prefix = "sam-fbla-01"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

